/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Modelo.forenKeys;
import Modelo.Conecion;
import coneciones.TestBD;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS_01
 */
public class Controladores extends javax.swing.JFrame {

    Properties propiedade;
    Conecion c;
    ArrayList<String> ListTable = new ArrayList();
    ArrayList<String> ListTable2 = new ArrayList();
    ArrayList<forenKeys> listForenKey = new ArrayList();
    String tablas = "";
    TestBD conecion;
    String folder;

    public Controladores(ArrayList<String> tablas,Properties p, Conecion c,String Folder) throws IOException, SQLException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.propiedade = p;
        coneciones.addItem(c.getNombre());
        mns.setText(".");
        conecion= new TestBD();
        this.folder=Folder;
        System.out.println("FOLDER de poojos : "+ Folder);
        ListTable2=tablas;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        coneciones = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mns = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        coneciones1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 578, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 369, 578, 10));

        coneciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conecionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conecionesMousePressed(evt);
            }
        });
        coneciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conecionesActionPerformed(evt);
            }
        });
        jPanel1.add(coneciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 420, -1));

        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel2.setText("Folder");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel1.add(mns, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 210, -1));

        jLabel3.setText("Templet");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 420, -1));

        jLabel4.setText("Date Base");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        coneciones1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basico", "Bootfaces" }));
        coneciones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coneciones1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coneciones1MousePressed(evt);
            }
        });
        coneciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coneciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(coneciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 420, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conecionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conecionesMouseClicked

    }//GEN-LAST:event_conecionesMouseClicked

    private void conecionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conecionesMousePressed

    }//GEN-LAST:event_conecionesMousePressed

    private void conecionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conecionesActionPerformed

    }//GEN-LAST:event_conecionesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        try {
            new CreacionJCM(ListTable2, true,propiedade,c,this.folder,jTextField1.getText(),coneciones1.getSelectedIndex()).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Controladores.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Controladores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void coneciones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coneciones1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_coneciones1MouseClicked

    private void coneciones1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coneciones1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_coneciones1MousePressed

    private void coneciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coneciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coneciones1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> coneciones;
    private javax.swing.JComboBox<String> coneciones1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mns;
    // End of variables declaration//GEN-END:variables
}
